easy_admin:
  site_name: 'Etoile de Marius'
  user:
    display_name: true
    display_avatar: true
    name_property_path: 'email'

  design:
    brand_color: '#003975'
    menu:
      - { label: 'Content' }
      - { entity: 'Cloth', permission: 'ROLE_ADMIN', label: 'Cloth', icon: 'tshirt' }
      - { entity: 'Mask', permission: 'ROLE_ADMIN', label: 'Mask', icon: 'mask' }
      - { entity: 'Pants', permission: 'ROLE_ADMIN', label: 'Pants', icon: 'socks' }
      - { label: 'Administration', permission: 'ROLE_ADMIN' }
      - { entity: 'User', permission: 'ROLE_ADMIN', label: 'Users', icon: 'user' }
      - { label: '____________________' }

  formats:
    date:     'd/m/Y'
    time:     'H:i'
    datetime: 'd/m/Y H:i:s'

  list:
    actions:
      # Add actions icons in list
      - { name: 'edit', icon: 'pencil' }
      - { name: 'delete', icon: 'trash' }

  entities:
    Cloth:
      class: App\Entity\Cloth
      label: Cloth
      help: |
        Pieces of cloth
      form:
        fields:
          - { property: 'name', type_options: { required: true } }
          - { property: 'picture', type: 'file', type_options: { required: true } }
          - { property: 'price', type_options: { required: true } }
          - { property: 'summary', type_options: { required: true} }
          - { property: 'description', type_options: { required: true} }
          - { property: 'published' }
      show:
        fields:
          - { property: 'id'}
          - { property: 'name'}
          - { property: 'picture', type: 'image' }
          - { property: 'price', type: 'money', type_options: { currency: 'EUR' } }
          - { property: 'summary' }
          - { property: 'description' }
        actions: ['-edit']
      list:
        actions: ['show', '-edit']
        fields:
          - { property: 'id'}
          - { property: 'name' }
          - { property: 'picture', type: 'image' }
          - { property: 'published' }
    Mask:
      class: App\Entity\Mask
      label: Mask
      help: |
        Some masks
      form:
        fields:
          - { property: 'name', type_options: { required: true } }
          - { property: 'picture', type: 'file', type_options: { required: true } }
          - { property: 'price', type_options: { required: true } }
          - { property: 'summary', type_options: { required: true} }
          - { property: 'description', type_options: { required: true} }
          - { property: 'published' }
      show:
        fields:
          - { property: 'id'}
          - { property: 'name'}
          - { property: 'picture', type: 'image' }
          - { property: 'price', type: 'money', type_options: { currency: 'EUR' } }
          - { property: 'summary' }
          - { property: 'description' }
        actions: ['-edit']
      list:
        actions: ['show', '-edit']
        fields:
          - { property: 'id'}
          - { property: 'name' }
          - { property: 'picture', type: 'image' }
          - { property: 'published' }
    Pants:
      class: App\Entity\Pants
      label: Pants
      help: |
        Some pants
      form:
        fields:
          - { property: 'name', type_options: { required: true } }
          - { property: 'picture', type: 'file', type_options: { required: true } }
          - { property: 'price', type_options: { required: true } }
          - { property: 'summary', type_options: { required: true} }
          - { property: 'description', type_options: { required: true} }
          - { property: 'published' }
      show:
        fields:
          - { property: 'id'}
          - { property: 'name'}
          - { property: 'picture', type: 'image' }
          - { property: 'price', type: 'money', type_options: { currency: 'EUR' } }
          - { property: 'summary' }
          - { property: 'description' }
        actions: ['-edit']
      list:
        actions: ['show', '-edit']
        fields:
          - { property: 'id'}
          - { property: 'name' }
          - { property: 'picture', type: 'image' }
          - { property: 'published' }

    # Backend users
    User:
      class: App\Entity\User
      controller: App\Controller\Admin\UserController
      label: User
      help: |
        Users can manage application.
      # We will have so few users that there is no reason to search on them
      disabled_actions: ['show', 'search']
      new:
        item_permission: 'ROLE_ADMIN'
        fields:
          - { type: 'section', label: 'User', icon: 'user', help: 'Must be unique. Must be a valid email address.' }
          - { property: 'email', type: 'email', type_options: { required: true } }
          - { type: 'section', label: 'Password', icon: 'key' }
          - { property: 'plainpassword', label: 'Password', type: 'password', type_options: { required: true } }
      edit:
        item_permission: 'ROLE_ADMIN'
        fields:
          - { type: 'section', label: 'User', icon: 'user' }
          - { property: 'email', type: 'email', type_options: { disabled: true } }
          - { type: 'section', label: 'Password', icon: 'key' }
          - { property: 'plainpassword', label: 'Password', type: 'password', help: 'If you fill this field, password will be updated accordingly. If you leave this field blank, password will remain the same.'}
      show:
        item_permission: 'ROLE_ADMIN'
      list:
        item_permission: 'ROLE_ADMIN'
        sort: ['email', 'ASC']
        fields:
          - username
          - roles
