easy_admin:
  site_name: 'Etoile de Marius'
  user:
    display_name: true
    display_avatar: true
    name_property_path: 'email'

  design:
    brand_color: '#003975'
    menu:
      - { label: 'Content' }
      - { label: 'Administration', permission: 'ROLE_ADMIN' }
      - { entity: 'User', permission: 'ROLE_ADMIN', label: 'Users', icon: 'user' }
      - { label: '____________________' }

  formats:
    date:     'd/m/Y'
    time:     'H:i'
    datetime: 'd/m/Y H:i:s'

  list:
    actions:
      # Add actions icons in list
      - { name: 'edit', icon: 'pencil' }
      - { name: 'delete', icon: 'trash' }

  entities:
    # Backend users
    User:
      class: App\Entity\User
      controller: App\Controller\Admin\UserController
      label: User
      help: |
        Users can manage application.
      # We will have so few users that there is no reason to search on them
      disabled_actions: ['show', 'search']
      new:
        item_permission: 'ROLE_ADMIN'
        fields:
          - { type: 'section', label: 'User', icon: 'user', help: 'Must be unique. Must be a valid email address.' }
          - { property: 'email', type: 'email', type_options: { required: true } }
          - { type: 'section', label: 'Password', icon: 'key' }
          - { property: 'plainpassword', label: 'Password', type: 'password', type_options: { required: true } }
      edit:
        item_permission: 'ROLE_ADMIN'
        fields:
          - { type: 'section', label: 'User', icon: 'user' }
          - { property: 'email', type: 'email', type_options: { disabled: true } }
          - { type: 'section', label: 'Password', icon: 'key' }
          - { property: 'plainpassword', label: 'Password', type: 'password', help: 'If you fill this field, password will be updated accordingly. If you leave this field blank, password will remain the same.'}
      show:
        item_permission: 'ROLE_ADMIN'
      list:
        item_permission: 'ROLE_ADMIN'
        sort: ['email', 'ASC']
        fields:
          - username
          - roles
